name: Build Release
on:
  push:
    tags:
      - 'v*.*.*'

  # Allow manual triggering of action
  workflow_dispatch:

jobs:
  create_image_RPI1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: output/raspberrypi/images/
          key: photos-RPI1-${{ github.sha }}
      - name: Build RPI1 image
        run: |
          mkdir -p output/raspberrypi/images/
          echo "Hello" > output/raspberrypi/images/photOS-raspberrypi.1.1.1.img.xz

        # ./build.sh raspberrypi
        # ./build.sh raspberrypi mkrelease
        # mv output/raspberrypi/images/photOS-raspberrypi*.img.xz images/
          
  create_image_RPI2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: output/raspberrypi2/images/
          key: photos-RPI2-${{ github.sha }}
      - name: Build RPI2 image
        run: |
          mkdir -p output/raspberrypi2/images/
          echo "World" > output/raspberrypi2/images/photOS-raspberrypi2.1.1.1.img.xz


# ./build.sh raspberrypi2
#          ./build.sh raspberrypi2 mkrelease
#          mv output/raspberrypi/images/photOS-raspberrypi*.img.xz images/

  create_image_RPI3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: output/raspberrypi3/images/
          key: photos-RPI3-${{ github.sha }}
      - name: Build RPI3 image
        run: |
          mkdir -p output/raspberrypi3/images/
          echo "Hallo" > output/raspberrypi3/images/photOS-raspberrypi3.1.1.1.img.xz

#./build.sh raspberrypi3
#          ./build.sh raspberrypi3 mkrelease
#          mv output/raspberrypi/images/photOS-raspberrypi*.img.xz images/

  create_image_RPI4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: output/raspberrypi4/images/
          key: photos-RPI4-${{ github.sha }}
      - name: Build RPI4 image
        run: |
          mkdir -p output/raspberrypi4/images/
          echo "Welt" > output/raspberrypi4/images/photOS-raspberrypi4.1.1.1.img.xz

#./build.sh raspberrypi4
#          ./build.sh raspberrypi4 mkrelease
#          mv output/raspberrypi/images/photOS-raspberrypi*.img.xz images/

  create_Release:
    needs: [ create_image_RPI1,  create_image_RPI2,  create_image_RPI3,  create_image_RPI4 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: output/raspberrypi/images/
          key: photos-RPI1-${{ github.sha }}
      - uses: actions/cache@v2
        with:
          path: output/raspberrypi2/images/
          key: photos-RPI2-${{ github.sha }}
      - uses: actions/cache@v2
        with:
          path: output/raspberrypi3/images/
          key: photos-RPI3-${{ github.sha }}
      - uses: actions/cache@v2
        with:
          path: output/raspberrypi4/images/
          key: photos-RPI4-${{ github.sha }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            output/raspberrypi/images/*.img.xz
            output/raspberrypi2/images/*.img.xz
            output/raspberrypi3/images/*.img.xz
            output/raspberrypi4/images/*.img.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
