name: Build Release
on:
  push:
    tags:
      - 'v*.*.*'

  # Allow manual triggering of action
  workflow_dispatch:

jobs:
  create_image_RPI1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: images
          key: photos-${{ github.sha }}
      - name: Build RPI1 image
        run: |
          ./build.sh raspberrypi
          ./build.sh raspberrypi mkrelease
          mv output/raspberrypi/images/photOS-raspberrypi*.img.xz images/
          
  create_image_RPI2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: images
          key: photos-${{ github.sha }}
      - name: Build RPI2 image
        run: |
          ./build.sh raspberrypi2
          ./build.sh raspberrypi2 mkrelease
          mv output/raspberrypi/images/photOS-raspberrypi*.img.xz images/

  create_image_RPI3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: images
          key: photos-${{ github.sha }}
      - name: Build RPI3 image
        run: |
          ./build.sh raspberrypi3
          ./build.sh raspberrypi3 mkrelease
          mv output/raspberrypi/images/photOS-raspberrypi*.img.xz images/

  create_image_RPI4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: images
          key: photos-${{ github.sha }}
      - name: Build RPI4 image
        run: |
          ./build.sh raspberrypi4
          ./build.sh raspberrypi4 mkrelease
          mv output/raspberrypi/images/photOS-raspberrypi*.img.xz images/

  create_Release
    needs: [ create_image_RPI1,  create_image_RPI2,  create_image_RPI3,  create_image_RPI4 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: images
          key: photos-${{ github.sha }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            /images/*.img.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
