name: Build Release
on:
  push:
    tags:
      - 'v*.*.*'

  # Allow manual triggering of action
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build RPI1 image
        run: |
          ./build.sh raspberrypi
          ./build.sh raspberrypi mkrelease
      - name: Build RPI1 image
        run: |
          ./build.sh raspberrypi2
          ./build.sh raspberrypi2 mkrelease
      - name: Build RPI2 image
        run: |
          ./build.sh raspberrypi3
          ./build.sh raspberrypi3 mkrelease
      - name: Build RPI1 image
        run: |
          ./build.sh raspberrypi4
          ./build.sh raspberrypi4 mkrelease
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            output/raspberrypi/images/photOS-raspberrypi-*.img.xz
            output/raspberrypi2/images/photOS-raspberrypi2-*.img.xz
            output/raspberrypi3/images/photOS-raspberrypi3-*.img.xz
            output/raspberrypi4/images/photOS-raspberrypi4-*.img.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
