name: Build Release
on:
  push:
    tags:
      - 'v*.*.*'

  # Allow manual triggering of action
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build RPI image
        run: ./build.sh raspberrypi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/raspberrypi/images/photOS-raspberrypi-*.img.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
